version: 1
source: google-trends

groups:
  - id: GT01
    name: category_language
    queries:
      - salon çiçeği
      - salon bitkisi
      - ev bitkisi
      - saksı çiçeği
      - saksılı bitki

  - id: GT02
    name: top_species
    queries:
      - starliçe
      - deve tabanı
      - paşa kılıcı
      - para ağacı
      - antoryum

  - id: GT03
    name: species_names_A
    queries:
      - deve tabanı
      - monstera
      - starliçe
      - strelitzia
      - cennet kuşu çiçeği

  - id: GT04
    name: species_names_B
    queries:
      - yuka çiçeği
      - yucca
      - kauçuk çiçeği
      - kauçuk bitkisi
      - ficus

  - id: GT05
    name: usecases
    queries:
      - ofis bitkileri
      - banyo bitkileri
      - yatak odası bitkileri
      - gölge seven bitkiler
      - büyük salon bitkileri
